#Componentes respectivos a MQTT
mqtt:
  usuario: PC_Test
  contrasena: Test1234
  url: c4e2607e9758412696b75708d95794bb.s1.eu.hivemq.cloud
  puerto: 8883
#Componentes respectivos a serial
serial:
  #Puerto correspondiente en el que se conectará el USB
  puerto: COM7
  #De aqui en adelante es probable que no se deban modificar, a menos de que los intruyan a hacerlo
  baudrate: 9600
  bytesize: 7
  parity: even
  stopbits: 1
  xonxoff: True
  timeout: 1
#Componentes respectivos a la informacion del cliente y del dispositivo
cliente:
  id_cliente: PC_Test
  id_panel: 1
  modelo_panel: Notifier NFS320
  id_modelo_panel: 10003
  coordenadas:
    latitud: 9.929289
    longitud: -84.104287