#Componentes respectivos a MQTT
mqtt:
  usuario: usuario
  contrasena: contrasena
  url: url
  puerto: 0000
#Componentes respectivos a serial
serial:
  #Puerto correspondiente en el que se conectará el USB
  puerto: "direccion/del/puerto"
  #De aqui en adelante es probable que no se deban modificar, a menos de que los intruyan a hacerlo
  baudrate: 9600
  bytesize: 8
  parity: 'N'
  stopbits: 1
  xonxoff: False
  timeout: 1
#Componentes respectivos a la informacion del cliente y del dispositivo
cliente:
  id_cliente: Test
  id_facp: '001'
  modelo_panel: Edward's iO1000
