---
#Evento y su respectivo nivel de severidad
HUMO ACT: 2
CALOR ACT: 2
DUCTO ACT: 2
EST MAN ACT: 2
FLUJ ACT: 2
COAL ACT: 2
ALRM ACT: 2
COSU ACT: 1
SUPV ACT: 1
COMO ACT: 1
MON ACT: 1
Salidas bloqueadas: 1
PALM ACT: 1
ALMV ACT: 1
MANT ACT: 1
FALL ACT: 0
DESH ACT: 0
PRBA ACT: 0
SMK ACT: 2
HEAT ACT: 2
DUCT ACT: 2
PULL ACT: 2
WFLW ACT: 2
PROB ACT: 1
Outputs are latched: 1
TRBL ACT: 0
DSBL ACT: 0
TEST ACT: 0
HUMO RST: 0
CALOR RST: 0
DUCTO RST: 0
EST MAN RST: 0
FLUJ RST: 0
COAL RST: 0
ALRM RST: 0
COSU RST: 0
SUPV RST: 0
COMO RST: 0
MON RST: 0
PALM RST: 0
ALMV RST: 0
MANT RST: 0
FALL RST: 0
DESH RST: 0
PRBA RST: 0
SMK RST: 0
HEAT RST: 0
DUCT RST: 0
PULL RST: 0
WFLW RST: 0
PROB RST: 0
TRBL RST: 0
DSBL RST: 0
TEST RST: 0