version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  file_handler_main:
    class: logging.FileHandler
    level: WARNING
    formatter: simple
    filename: main.log  
  file_handler_serial:
    class: logging.FileHandler
    level: WARNING
    formatter: simple
    filename: serial_reader.log  
  file_handler_mqtt:
    class: logging.FileHandler
    level: WARNING
    formatter: simple
    filename: mqtt_sender.log  
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  __main__:
    level: DEBUG
    handlers: [file_handler_main, console_handler]
    propagate: no
  serial_reader:
    level: DEBUG
    handlers: [file_handler_serial, console_handler]
    propagate: no
  mqtt_sender:
    level: DEBUG
    handlers: [file_handler_mqtt, console_handler]
    propagate: no
root:
  level: DEBUG
  handlers: [console_handler]
